[package]
name = "mergesort"
version = "0.1.0"
authors = ["Ben Bariteau <\"ben.bariteau@gmail.com\">"]

[dependencies]
serde_json = "^1.0.0"
serde_derive = "^1.0.0"
serde = "^1.0.0"
itertools = "^0.8.0"
